import type { Decorator, Meta, StoryObj } from '@storybook/react';
import { FlyOverClosestPanel } from './FlyOverClosestPanel';
import type { Aircraft, FlyOverResult } from '../api/types';

function aircraft(overrides: Partial<Aircraft> & Pick<Aircraft, 'icao24' | 'callsign'>): Aircraft {
  return {
    originAirport: null,
    originCity: null,
    originAirportName: null,
    originCountry: null,
    destinationAirport: null,
    destinationCity: null,
    destinationAirportName: null,
    destinationCountry: null,
    latitude: 48.9211,
    longitude: 2.4288,
    altitude: 9144,
    onGround: false,
    velocity: 251.2,
    trueTrack: 87.5,
    verticalRate: 0,
    distanceKm: 8.2,
    ...overrides,
  };
}

const dlh = aircraft({ icao24: '3c6444', callsign: 'DLH400', distanceKm: 8.2 });
const ryr = aircraft({ icao24: '4ca866', callsign: 'RYR45A', distanceKm: 26.1 });
const tap = aircraft({ icao24: '4951a1', callsign: 'TAP123', distanceKm: 40.5 });

const manyFlights: Aircraft[] = [
  aircraft({
    icao24: '39c421',
    callsign: 'AFR123',
    distanceKm: 6.4,
    latitude: 48.8731,
    longitude: 2.4102,
    altitude: 4877,
    velocity: 214.5,
    trueTrack: 274.3,
    verticalRate: 3.2,
    originAirport: 'LFPG',
    originCity: 'Paris',
    originAirportName: 'Paris Charles de Gaulle',
    originCountry: 'France',
    destinationAirport: 'EGLL',
    destinationCity: 'London',
    destinationAirportName: 'London Heathrow',
    destinationCountry: 'United Kingdom',
  }),
  aircraft({
    icao24: '400a1b',
    callsign: 'BAW456',
    distanceKm: 9.1,
    latitude: 48.8902,
    longitude: 2.2874,
    altitude: 9754,
    velocity: 246.8,
    trueTrack: 91.7,
    originAirport: 'EGLL',
    originCity: 'London',
    originAirportName: 'London Heathrow',
    originCountry: 'United Kingdom',
    destinationAirport: 'LFPG',
    destinationCity: 'Paris',
    destinationAirportName: 'Paris Charles de Gaulle',
    destinationCountry: 'France',
  }),
  aircraft({
    icao24: '3c6444',
    callsign: 'DLH400',
    distanceKm: 12.7,
    latitude: 48.8124,
    longitude: 2.4601,
    altitude: 11278,
    velocity: 258.3,
    trueTrack: 178.9,
    originAirport: 'EDDF',
    originCity: 'Frankfurt',
    originAirportName: 'Frankfurt Airport',
    originCountry: 'Germany',
    destinationAirport: 'LFPG',
    destinationCity: 'Paris',
    destinationAirportName: 'Paris Charles de Gaulle',
    destinationCountry: 'France',
  }),
  aircraft({
    icao24: '4ca866',
    callsign: 'RYR45A',
    distanceKm: 15.3,
    latitude: 48.9256,
    longitude: 2.1908,
    altitude: 8230,
    velocity: 233.1,
    trueTrack: 42.6,
    verticalRate: -2.1,
    originAirport: 'EIDW',
    originCity: 'Dublin',
    originAirportName: 'Dublin Airport',
    originCountry: 'Ireland',
    destinationAirport: 'LFPG',
    destinationCity: 'Paris',
    destinationAirportName: 'Paris Charles de Gaulle',
    destinationCountry: 'France',
  }),
  aircraft({
    icao24: '406b2c',
    callsign: 'EZY789',
    distanceKm: 17.9,
    latitude: 48.7698,
    longitude: 2.3388,
    altitude: 7010,
    velocity: 226.4,
    trueTrack: 315.2,
    verticalRate: 1.4,
    originAirport: 'EGKK',
    originCity: 'London',
    originAirportName: 'London Gatwick',
    originCountry: 'United Kingdom',
    destinationAirport: 'LFLL',
    destinationCity: 'Lyon',
    destinationAirportName: 'Lyon–Saint-Exupéry',
    destinationCountry: 'France',
  }),
  aircraft({
    icao24: '484506',
    callsign: 'KLM64',
    distanceKm: 20.2,
    latitude: 48.9543,
    longitude: 2.5117,
    altitude: 10363,
    velocity: 251.9,
    trueTrack: 137.5,
    originAirport: 'EHAM',
    originCity: 'Amsterdam',
    originAirportName: 'Amsterdam Schiphol',
    originCountry: 'Netherlands',
    destinationAirport: 'LFPO',
    destinationCity: 'Paris',
    destinationAirportName: 'Paris Orly',
    destinationCountry: 'France',
  }),
  aircraft({
    icao24: '4b1814',
    callsign: 'SWR88',
    distanceKm: 22.6,
    latitude: 48.7412,
    longitude: 2.571,
    altitude: 11582,
    velocity: 264.7,
    trueTrack: 204.8,
    originAirport: 'LSZH',
    originCity: 'Zurich',
    originAirportName: 'Zurich Airport',
    originCountry: 'Switzerland',
    destinationAirport: 'EGLL',
    destinationCity: 'London',
    destinationAirportName: 'London Heathrow',
    destinationCountry: 'United Kingdom',
  }),
  aircraft({
    icao24: '3461c8',
    callsign: 'IBE31',
    distanceKm: 24.8,
    latitude: 48.9876,
    longitude: 2.162,
    altitude: 6401,
    velocity: 219.6,
    trueTrack: 21.3,
    verticalRate: 4.7,
    originAirport: 'LEMD',
    originCity: 'Madrid',
    originAirportName: 'Adolfo Suárez Madrid–Barajas',
    originCountry: 'Spain',
    destinationAirport: 'LFPG',
    destinationCity: 'Paris',
    destinationAirportName: 'Paris Charles de Gaulle',
    destinationCountry: 'France',
  }),
  aircraft({
    icao24: '4951a1',
    callsign: 'TAP123',
    distanceKm: 27.4,
    latitude: 48.7001,
    longitude: 2.2199,
    altitude: 8839,
    velocity: 241.2,
    trueTrack: 256.4,
    originAirport: 'LPPT',
    originCity: 'Lisbon',
    originAirportName: 'Humberto Delgado Airport',
    originCountry: 'Portugal',
    destinationAirport: 'EHAM',
    destinationCity: 'Amsterdam',
    destinationAirportName: 'Amsterdam Schiphol',
    destinationCountry: 'Netherlands',
  }),
  aircraft({
    icao24: '4ba9d4',
    callsign: 'THY5',
    distanceKm: 29.9,
    latitude: 49.0124,
    longitude: 2.3977,
    altitude: 10668,
    velocity: 256,
    trueTrack: 118.1,
    originAirport: 'LTFM',
    originCity: 'Istanbul',
    originAirportName: 'Istanbul Airport',
    originCountry: 'Türkiye',
    destinationAirport: 'LFPG',
    destinationCity: 'Paris',
    destinationAirportName: 'Paris Charles de Gaulle',
    destinationCountry: 'France',
  }),
  aircraft({
    icao24: '4400a1',
    callsign: 'AUA21',
    distanceKm: 32.3,
    latitude: 48.6634,
    longitude: 2.4902,
    altitude: 5212,
    velocity: 198.7,
    trueTrack: 289.6,
    verticalRate: -3.8,
    originAirport: 'LOWW',
    originCity: 'Vienna',
    originAirportName: 'Vienna International',
    originCountry: 'Austria',
    destinationAirport: 'LFPO',
    destinationCity: 'Paris',
    destinationAirportName: 'Paris Orly',
    destinationCountry: 'France',
  }),
  aircraft({
    icao24: '4a0a2b',
    callsign: 'SAS903',
    distanceKm: 34.7,
    latitude: 48.9998,
    longitude: 2.6801,
    altitude: 12192,
    velocity: 268.9,
    trueTrack: 156.2,
    originAirport: 'EKCH',
    originCity: 'Copenhagen',
    originAirportName: 'Copenhagen Airport',
    originCountry: 'Denmark',
    destinationAirport: 'LFPG',
    destinationCity: 'Paris',
    destinationAirportName: 'Paris Charles de Gaulle',
    destinationCountry: 'France',
  }),
  aircraft({
    icao24: 'a1b2c3',
    callsign: 'AAL100',
    distanceKm: 37.1,
    latitude: 48.6187,
    longitude: 2.1233,
    altitude: 9450,
    velocity: 249.5,
    trueTrack: 63.8,
    originAirport: 'KJFK',
    originCity: 'New York',
    originAirportName: 'John F. Kennedy International',
    originCountry: 'United States',
    destinationAirport: 'LFPG',
    destinationCity: 'Paris',
    destinationAirportName: 'Paris Charles de Gaulle',
    destinationCountry: 'France',
  }),
  aircraft({
    icao24: 'a4d5e6',
    callsign: 'DAL49',
    distanceKm: 39.4,
    latitude: 49.0455,
    longitude: 2.244,
    altitude: 11887,
    velocity: 262.1,
    trueTrack: 231.9,
    originAirport: 'KATL',
    originCity: 'Atlanta',
    originAirportName: 'Hartsfield–Jackson Atlanta International',
    originCountry: 'United States',
    destinationAirport: 'LFPG',
    destinationCity: 'Paris',
    destinationAirportName: 'Paris Charles de Gaulle',
    destinationCountry: 'France',
  }),
  aircraft({
    icao24: '8963f7',
    callsign: 'UAE202',
    distanceKm: 41.8,
    latitude: 48.582,
    longitude: 2.6309,
    altitude: 10973,
    velocity: 254.8,
    trueTrack: 342.7,
    originAirport: 'OMDB',
    originCity: 'Dubai',
    originAirportName: 'Dubai International',
    originCountry: 'United Arab Emirates',
    destinationAirport: 'KJFK',
    destinationCity: 'New York',
    destinationAirportName: 'John F. Kennedy International',
    destinationCountry: 'United States',
  }),
  aircraft({
    icao24: '06a0b8',
    callsign: 'QTR7',
    distanceKm: 44.2,
    latitude: 49.0771,
    longitude: 2.5512,
    altitude: 12497,
    velocity: 271.3,
    trueTrack: 12.4,
    originAirport: 'OTHH',
    originCity: 'Doha',
    originAirportName: 'Hamad International',
    originCountry: 'Qatar',
    destinationAirport: 'EGLL',
    destinationCity: 'London',
    destinationAirportName: 'London Heathrow',
    destinationCountry: 'United Kingdom',
  }),
  aircraft({
    icao24: '76c9d0',
    callsign: 'SIA26',
    distanceKm: 46.5,
    latitude: 48.5503,
    longitude: 2.0714,
    altitude: 11582,
    velocity: 259.7,
    trueTrack: 286,
    originAirport: 'WSSS',
    originCity: 'Singapore',
    originAirportName: 'Singapore Changi',
    originCountry: 'Singapore',
    destinationAirport: 'EDDF',
    destinationCity: 'Frankfurt',
    destinationAirportName: 'Frankfurt Airport',
    destinationCountry: 'Germany',
  }),
  aircraft({
    icao24: '780e1f',
    callsign: 'CPA88',
    distanceKm: 47.9,
    latitude: 49.1012,
    longitude: 2.1201,
    altitude: 10363,
    velocity: 253.4,
    trueTrack: 75.5,
    originAirport: 'VHHH',
    originCity: 'Hong Kong',
    originAirportName: 'Hong Kong International',
    originCountry: 'Hong Kong',
    destinationAirport: 'LFPG',
    destinationCity: 'Paris',
    destinationAirportName: 'Paris Charles de Gaulle',
    destinationCountry: 'France',
  }),
  aircraft({
    icao24: '86f0a2',
    callsign: 'JAL44',
    distanceKm: 48.6,
    latitude: 48.531,
    longitude: 2.7023,
    altitude: 9754,
    velocity: 247.1,
    trueTrack: 198.3,
    originAirport: 'RJTT',
    originCity: 'Tokyo',
    originAirportName: 'Tokyo Haneda',
    originCountry: 'Japan',
    destinationAirport: 'EGLL',
    destinationCity: 'London',
    destinationAirportName: 'London Heathrow',
    destinationCountry: 'United Kingdom',
  }),
  aircraft({
    icao24: 'c0ffee',
    callsign: 'ACA33',
    distanceKm: 49.5,
    latitude: 49.118,
    longitude: 2.43,
    altitude: 11278,
    velocity: 260.6,
    trueTrack: 52.9,
    originAirport: 'CYYZ',
    originCity: 'Toronto',
    originAirportName: 'Toronto Pearson International',
    originCountry: 'Canada',
    destinationAirport: 'LFPG',
    destinationCity: 'Paris',
    destinationAirportName: 'Paris Charles de Gaulle',
    destinationCountry: 'France',
  }),
];

function result(aircraftList: Aircraft[]): FlyOverResult {
  return {
    center: { lat: 48.8566, lng: 2.3522 },
    radiusKm: 50,
    asOf: 1_726_900_000,
    count: aircraftList.length,
    destinationEnrichment: 'complete',
    aircraft: aircraftList,
  };
}

/** Point the panel's fetch at a fixture so stories render offline deterministically. */
function installFetchStub(body: unknown, status = 200): void {
  window.fetch = (() =>
    Promise.resolve(
      new Response(JSON.stringify(body), {
        status,
        headers: { 'Content-Type': 'application/json' },
      }),
    )) as typeof fetch;
}

function withFetchStub(body: unknown, status = 200): Decorator {
  return (Story) => {
    installFetchStub(body, status);
    return (
      <div className="h-[560px] w-full max-w-2xl">
        <Story />
      </div>
    );
  };
}

const meta: Meta<typeof FlyOverClosestPanel> = {
  title: 'DashboardWidgets/FlyOverClosestPanel',
  component: FlyOverClosestPanel,
  args: {
    location: { lat: 48.8566, lng: 2.3522, radiusKm: 50 },
  },
};

export default meta;
type Story = StoryObj<typeof meta>;

export const WithAircraft: Story = {
  decorators: [withFetchStub(result([dlh, ryr, tap]))],
};

export const CappedList: Story = {
  args: { maxResults: 1 },
  decorators: [withFetchStub(result([dlh, ryr, tap]))],
};

export const Empty: Story = {
  decorators: [withFetchStub(result([]))],
};

export const Error: Story = {
  decorators: [
    withFetchStub({ success: false, message: 'Aircraft feed is temporarily unavailable' }, 503),
  ],
};

export const AutoRefresh: Story = {
  args: { autoRefresh: 10 },
  decorators: [withFetchStub(result([dlh, ryr, tap]))],
};

export const ManyFlights: Story = {
  decorators: [withFetchStub(result(manyFlights))],
};
